version: "3.8"

services:
  gsky_memcached:
    image: memcached:${MEMCACHED_TAG}
    container_name: gsky_memcached
    ports:
     - 11211
  gsky_server:
    image: eahazardswatch.icpac.net/gsky:${GSKY_SERVER_TAG}
    container_name: gsky_server
    restart: ${RESTART_POLICY}
    command: sh /gsky_entrypoint.sh && sh/ingest.sh
    volumes:
      - ${HOST_DATA_ROOT_PATH}:/gdata
      - ${GSKY_CONFIG_FILE}:/gsky/etc/config.json
      - ${GSKY_INGEST_SCRIPT}:/ingest.sh
      - ./gsky/templates/WMS_GetCapabilities.tpl:/gsky/share/gsky/templates/WMS_GetCapabilities.tpl
      - ./gsky/templates/WPS_GetCapabilities.tpl:/gsky/share/gsky/templates/WPS_GetCapabilities.tpl
      - ./gsky/templates/WCS_GetCapabilities.tpl:/gsky/share/gsky/templates/WCS_GetCapabilities.tpl
      - ${GSKY_WPS_TEMPLATES_VOLUME}:/templates/WPS
      - ./gsky/rulesets:/rulesets
    environment: 
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
      - WEBHOOK_ENABLED=true
      - MEMCACHE_URI=gsky_memcached:11211
      - MEMCACHE_DEV_TCP_FILE=gsky_memcached/11211
      - MAS_DB_POOL_SIZE=8
    ports:
      - 8080
      - 8888
  gsky_manager_db:
    image: postgres:12
    container_name: gsky_manager_db
    restart: ${RESTART_POLICY}
    volumes:
      - gsky_db_data:/var/lib/postgresql/data/
    environment: 
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - 5432
  gsky_manager:
    image: eahazardswatch.icpac.net/gsky-manager:${GSKY_MANAGER_TAG}
    container_name: gsky_manager
    restart: ${RESTART_POLICY}
    command: gunicorn gskymanager.wsgi:application --workers=5 --threads=2 --bind 0.0.0.0:8000
    volumes:
      - ${HOST_DATA_ROOT_PATH}:/gdata
      - ${GSKY_INGEST_SCRIPT}:/scripts/ingest.sh
      - ${GSKY_CONFIG_FILE}:/gsky/config.json
      - ${GSKY_WPS_TEMPLATES_VOLUME}:/gsky/templates/WPS
      - gsky_mg_static:/home/app/web/static
      - gsky_mg_media:/home/app/web/media
      - ${FIXTURES_VOLUME}:/fixtures
      - ${DATA_SOURCE_VOLUME}:/data_source
      - ./gsky/rulesets:/gsky/rulesets
    environment:
      - CURRENT_UID=${CURRENT_UID} 
      - DEBUG=${DEBUG}
      - FORCE_SCRIPT_NAME=${FORCE_SCRIPT_NAME}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASS}@gsky_manager_db:5432/${DB_NAME}
      - HOST_DATA_ROOT_PATH=/gdata
      - CONTAINER_DATA_ROOT_PATH=/gdata
      - GSKY_CONFIG_FILE=/gsky/config.json
      - GSKY_OWS_HOST_NAME=${GSKY_OWS_HOST_NAME}
      - GSKY_OWS_PROTOCOL=${GSKY_OWS_PROTOCOL}
      - GSKY_MAS_ADDRESS=gsky_server:8888
      - GSKY_WORKER_NODES=gsky_server:6000
      - GSKY_INGEST_SCRIPT=/scripts/ingest.sh
      - GSKY_WPS_TEMPLATES_HOST_PATH=/gsky/templates/WPS
      - GSKY_WPS_TEMPLATES_CONTAINER_PATH=/templates/WPS
      - GSKY_RULESETS_HOST_PATH=/gsky/rulesets
      - GSKY_RULESETS_CONTAINER_PATH=/rulesets
      - GSKY_WEBHOOK_URL=http://gsky_server:9000/hooks
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
      - ADS_KEY=${ADS_KEY}
      - OWS_BASE_URL=${OWS_BASE_URL}
    ports:
      - 8000
  gsky_node:
    image: eahazardswatch.icpac.net/gsky-node:${GSKY_NODE_TAG}
    container_name: gsky_node
    restart: ${RESTART_POLICY}
    environment: 
      - GSKY_OWS_URL=http://gsky_server:8080/ows
      - GSKY_MAS_URL=http://gsky_server:8888
    ports:
      - 3000
  gsky_nginx:
    image: nginx:1.18.0-alpine
    restart: ${RESTART_POLICY}
    container_name: gsky_nginx
    volumes: 
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - gsky_mg_static:/gsky/static
      - gsky_mg_media:/gsky/media
    ports:
      - ${GSKY_NGINX_PORT}:80

volumes:
  gsky_db_data:
  gsky_mg_static:
  gsky_mg_media: