version: "3.8"

services:
  gsky_server:
    image: eahazardswatch.icpac.net/gsky:${GSKY_SERVER_TAG}
    container_name: gsky_server
    command: /bin/sh -c "/gsky_entrypoint.sh"
    volumes:
      - ${HOST_DATA_ROOT_PATH}:/gdata
      - ${GSKY_CONFIG_FILE}:/gsky/etc/config.json
      - gsky_mas_db:/pg_data
      - ./gsky/templates/WMS_GetCapabilities.tpl:/gsky/share/gsky/templates/WMS_GetCapabilities.tpl
    ports:
      - ${OWS_PORT}:8080
      - ${MAS_PORT}:8888
  gsky_manager_db:
    image: postgres:12
    container_name: gsky_manager_db
    volumes:
      - gsky_db_data:/var/lib/postgresql/data/
    environment: 
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - 5432
  gsky_manager:
    image: eahazardswatch.icpac.net/gsky-manager:${GSKY_MANAGER_TAG}
    container_name: gsky_manager
    command: gunicorn gskymanager.wsgi:application --workers=5 --threads=2 --bind 0.0.0.0:8000
    volumes:
      - ${HOST_DATA_ROOT_PATH}:/gdata
      - ${GSKY_CONFIG_FILE}:/gsky/config.json
      - gsky_mg_static:/home/app/web/static
      - gsky_mg_media:/home/app/web/media
      - ${FIXTURES_VOLUME}:/fixtures
      - ${DATA_SOURCE_VOLUME}:/data_source
    environment: 
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASS}@gsky_manager_db:5432/${DB_NAME}
      - HOST_DATA_ROOT_PATH=${HOST_DATA_ROOT_PATH}
      - CONTAINER_DATA_ROOT_PATH=/gdata
      - GSKY_CONFIG_FILE=${GSKY_CONFIG_FILE}
      - GSKY_OWS_HOST_NAME=gsky_server:${OWS_PORT}
      - GSKY_MAS_ADDRESS=gsky_server:${MAS_PORT}
      - GSKY_WORKER_NODES=gsky_server:6000
    ports:
      - ${MANAGER_PORT}:8000

volumes:
  gsky_db_data:
  gsky_mg_static:
  gsky_mg_media:
  gsky_mas_db: